services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cognify_academy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/cognify_academy?schema=public"
      JWT_SECRET: "your-jwt-secret-key-here"
      JWT_REFRESH_SECRET: "your-jwt-refresh-secret-key-here"
      NODE_ENV: "production"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3333/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
