services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: cognifyacademy
      POSTGRES_PASSWORD: localpassword
      POSTGRES_DB: cognifyacademy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # api:
  #   build:
  #     context: .
  #     dockerfile: apps/api/Dockerfile
  #   ports:
  #     - "3333:3333"
  #   environment:
  #     DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/cognify_academy?schema=public"
  #     JWT_SECRET: "your-jwt-secret-key-here"
  #     JWT_REFRESH_SECRET: "your-jwt-refresh-secret-key-here"
  #     NODE_ENV: "production"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:3333/api/v1/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

volumes:
  postgres_data:
