"use client";

import { useAuth } from "@/contexts/auth";
import idl from "@/lib/certificate_nft.json";
import { AnchorProvider, Program } from "@coral-xyz/anchor";
import {
  ASSOCIATED_TOKEN_PROGRAM_ID,
  getAssociatedTokenAddressSync,
  TOKEN_PROGRAM_ID,
} from "@solana/spl-token";
import { useConnection, useWallet } from "@solana/wallet-adapter-react";
import { WalletMultiButton } from "@solana/wallet-adapter-react-ui";
import {
  Keypair,
  PublicKey,
  SystemProgram,
  SYSVAR_RENT_PUBKEY,
} from "@solana/web3.js";
import { useState } from "react";

// Metaplex Token Metadata Program ID
const TOKEN_METADATA_PROGRAM_ID = new PublicKey(
  "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s",
);

// Helper to find metadata PDA
function findMetadataPDA(mint: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [
      Buffer.from("metadata"),
      TOKEN_METADATA_PROGRAM_ID.toBuffer(),
      mint.toBuffer(),
    ],
    TOKEN_METADATA_PROGRAM_ID,
  );
}

interface CertificateRequestProps {
  courseId: string;
  courseTitle: string;
  onSuccess?: (certificateData: any) => void;
}

export function CertificateRequestV2({
  courseId,
  courseTitle,
  onSuccess,
}: CertificateRequestProps) {
  const { publicKey, signTransaction } = useWallet();
  const { connection } = useConnection();
  const { user, accessToken } = useAuth();
  const [isRequesting, setIsRequesting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState(false);
  const [txSignature, setTxSignature] = useState<string>("");

  const handleRequestCertificate = async () => {
    if (!publicKey || !signTransaction) {
      setError("Please connect your wallet first");
      return;
    }

    if (!user || !accessToken) {
      setError("You must be logged in to request a certificate");
      return;
    }

    setIsRequesting(true);
    setError(null);

    try {
      // Create a dummy wallet for the provider (we'll use the connected wallet for signing)
      const dummyWallet = {
        publicKey,
        signTransaction,
        signAllTransactions: async (txs: any[]) => txs,
      };

      const provider = new AnchorProvider(connection, dummyWallet as any, {
        commitment: "confirmed",
      });

      // Initialize the program
      const program = new Program(idl as any, provider);

      // Generate new mint keypair for the NFT
      const mint = Keypair.generate();

      // Derive metadata PDA
      const [metadataPda] = findMetadataPDA(mint.publicKey);

      // Derive associated token account for the student
      const tokenAccount = getAssociatedTokenAddressSync(
        mint.publicKey,
        publicKey, // Student's wallet is the recipient
        false,
        TOKEN_PROGRAM_ID,
        ASSOCIATED_TOKEN_PROGRAM_ID,
      );

      // Certificate metadata
      // Metaplex has a 32-character limit for names
      const maxNameLength = 32;
      const suffix = " Cert";
      const maxTitleLength = maxNameLength - suffix.length;

      const truncatedTitle =
        courseTitle.length > maxTitleLength
          ? courseTitle.substring(0, maxTitleLength - 3) + "..."
          : courseTitle;

      const certificateName = truncatedTitle + suffix;
      const symbol = "COGCERT";

      // Use API URL for verification endpoint
      // The mint address is available now and uniquely identifies this certificate
      const apiUrl =
        process.env.NEXT_PUBLIC_API_URL || "http://localhost:3333/api/v1";
      const metadataUri = `${apiUrl}/certificates/nft/${mint.publicKey.toBase58()}`;

      const vcHash = "pending"; // Will be generated by API after minting

      console.log("Minting certificate NFT:");
      console.log("  Mint:", mint.publicKey.toBase58());
      console.log("  Student Wallet:", publicKey.toBase58());
      console.log("  Token Account:", tokenAccount.toBase58());
      console.log("  Metadata PDA:", metadataPda.toBase58());
      console.log(
        "  Certificate Name:",
        certificateName,
        `(${certificateName.length} chars)`,
      );

      // Build the transaction
      const tx = await program.methods
        .issueCertificate(metadataUri, certificateName, symbol, vcHash)
        .accounts({
          mint: mint.publicKey,
          recipient: publicKey,
          tokenAccount: tokenAccount,
          mintAuthority: publicKey, // Student is the mint authority
          metadata: metadataPda,
          metadataProgram: TOKEN_METADATA_PROGRAM_ID,
          tokenProgram: TOKEN_PROGRAM_ID,
          associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
          rent: SYSVAR_RENT_PUBKEY,
        })
        .signers([mint]) // Mint keypair must sign
        .transaction();

      // Get recent blockhash
      const { blockhash } = await connection.getLatestBlockhash();
      tx.recentBlockhash = blockhash;
      tx.feePayer = publicKey;

      // Sign with mint keypair first
      tx.partialSign(mint);

      // Have wallet sign the transaction (student pays)
      const signedTx = await signTransaction(tx);

      // Send and confirm the transaction
      const signature = await connection.sendRawTransaction(
        signedTx.serialize(),
      );

      console.log("Transaction sent:", signature);
      console.log("Waiting for confirmation...");

      // Wait for confirmation
      await connection.confirmTransaction(signature, "confirmed");

      console.log("Transaction confirmed:", signature);
      console.log("NFT minted successfully!");
      console.log("NFT Address:", mint.publicKey.toBase58());

      setTxSignature(signature);

      // Now call the API to store the certificate record
      const response = await fetch(`${apiUrl}/certificates/issue`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${accessToken}`,
        },
        body: JSON.stringify({
          userId: user.id,
          courseId: courseId,
          studentDid: `did:sol:${publicKey.toBase58()}`,
          studentWallet: publicKey.toBase58(),
          txSignature: signature,
          nftAddress: mint.publicKey.toBase58(),
        }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.message || "Failed to store certificate");
      }

      const certificateData = await response.json();
      console.log("Certificate stored:", certificateData);

      setSuccess(true);
      if (onSuccess) {
        onSuccess(certificateData);
      }
    } catch (err: any) {
      console.error("Error requesting certificate:", err);
      setError(err.message || "Failed to request certificate");
    } finally {
      setIsRequesting(false);
    }
  };

  if (success) {
    return (
      <div className="rounded-lg border border-green-200 bg-green-50 p-6 dark:border-green-800 dark:bg-green-900/20">
        <div className="flex items-start space-x-3">
          <svg
            className="mt-0.5 h-6 w-6 flex-shrink-0 text-green-600 dark:text-green-400"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
            />
          </svg>
          <div className="flex-1">
            <h3 className="font-semibold text-green-900 dark:text-green-100">
              Certificate Issued Successfully! 🎉
            </h3>
            <p className="mt-2 text-sm text-green-800 dark:text-green-200">
              Your completion certificate for{" "}
              <span className="font-medium">{courseTitle}</span> has been minted
              as a soulbound NFT. Check your wallet to view it!
            </p>
            <p className="mt-3 text-xs text-green-700 dark:text-green-300">
              Transaction:{" "}
              <span className="font-mono">
                {txSignature.slice(0, 8)}...{txSignature.slice(-8)}
              </span>
            </p>
            <p className="mt-1 text-xs text-green-700 dark:text-green-300">
              This certificate is permanently stored on the blockchain and
              cannot be transferred, ensuring authenticity and ownership.
            </p>
          </div>
        </div>
      </div>
    );
  }

  if (!publicKey) {
    return (
      <div className="rounded-lg border border-blue-200 bg-blue-50 p-6 dark:border-blue-800 dark:bg-blue-900/20">
        <div className="flex flex-col items-center space-y-4 text-center">
          <svg
            className="h-12 w-12 text-blue-600 dark:text-blue-400"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"
            />
          </svg>
          <div>
            <h3 className="font-semibold text-blue-900 dark:text-blue-100">
              Request Your Certificate
            </h3>
            <p className="mt-2 text-sm text-blue-800 dark:text-blue-200">
              Congratulations on completing <strong>{courseTitle}</strong>!
            </p>
            <p className="mt-2 text-sm text-blue-700 dark:text-blue-300">
              Connect your Solana wallet to mint your certificate NFT.
            </p>
            <p className="mt-1 text-xs text-blue-600 dark:text-blue-400">
              Cost: ~0.0015 SOL (~$0.20)
            </p>
          </div>
          <WalletMultiButton className="!bg-blue-600 hover:!bg-blue-700" />
        </div>
      </div>
    );
  }

  return (
    <div className="rounded-lg border border-purple-200 bg-purple-50 p-6 dark:border-purple-800 dark:bg-purple-900/20">
      <div className="flex items-start space-x-4">
        <div className="flex-shrink-0">
          <svg
            className="h-10 w-10 text-purple-600 dark:text-purple-400"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M9 12l2 2 4-4M7.835 4.697a3.42 3.42 0 001.946-.806 3.42 3.42 0 014.438 0 3.42 3.42 0 001.946.806 3.42 3.42 0 013.138 3.138 3.42 3.42 0 00.806 1.946 3.42 3.42 0 010 4.438 3.42 3.42 0 00-.806 1.946 3.42 3.42 0 01-3.138 3.138 3.42 3.42 0 00-1.946.806 3.42 3.42 0 01-4.438 0 3.42 3.42 0 00-1.946-.806 3.42 3.42 0 01-3.138-3.138 3.42 3.42 0 00-.806-1.946 3.42 3.42 0 010-4.438 3.42 3.42 0 00.806-1.946 3.42 3.42 0 013.138-3.138z"
            />
          </svg>
        </div>
        <div className="flex-1">
          <h3 className="font-semibold text-purple-900 dark:text-purple-100">
            Mint Your Certificate NFT
          </h3>
          <p className="mt-2 text-sm text-purple-800 dark:text-purple-200">
            Click below to mint your completion certificate as a soulbound NFT.
            <strong> You'll pay for the minting cost</strong> (~0.0015 SOL or
            ~$0.20).
          </p>
          <p className="mt-2 text-xs text-purple-700 dark:text-purple-300">
            Connected: {publicKey.toBase58().slice(0, 4)}...
            {publicKey.toBase58().slice(-4)}
          </p>

          {error && (
            <div className="mt-3 rounded-md bg-red-100 p-3 dark:bg-red-900/30">
              <p className="text-sm text-red-800 dark:text-red-200">{error}</p>
            </div>
          )}

          <button
            onClick={handleRequestCertificate}
            disabled={isRequesting}
            className="mt-4 inline-flex items-center rounded-lg bg-purple-600 px-6 py-3 text-sm font-semibold text-white transition-colors hover:bg-purple-700 disabled:cursor-not-allowed disabled:bg-purple-400 dark:bg-purple-500 dark:hover:bg-purple-600"
          >
            {isRequesting ? (
              <>
                <svg
                  className="mr-2 h-4 w-4 animate-spin"
                  fill="none"
                  viewBox="0 0 24 24"
                >
                  <circle
                    className="opacity-25"
                    cx="12"
                    cy="12"
                    r="10"
                    stroke="currentColor"
                    strokeWidth="4"
                  />
                  <path
                    className="opacity-75"
                    fill="currentColor"
                    d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                  />
                </svg>
                Minting NFT...
              </>
            ) : (
              <>
                <svg
                  className="mr-2 h-4 w-4"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
                  />
                </svg>
                Mint Certificate NFT (~$0.20)
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}
